### ISSUE TITLE
Justin's Use/Misuse Case

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#17]

**Comment by JustinRobbins7** [comment]
Completed misuse case diagram.

**Comment by JustinRobbins7** [comment]
Completed my misuse case section, feel free to proofread and give feedback.

**Comment by JustinRobbins7** [comment]
Updated my use/misuse case to match the format of the other case in the paper

**Comment by jnallou** [comment]
Hey Justin, your diagram looks good. Great summary for the use case.

**Comment by MSMareddy** [comment]
^ Great summary, I think this issue is good to go. @JustinRobbins7

**Comment by malhuneidi** [comment]
Looks great!
