### ISSUE TITLE
Joel's Use/Misuse Case

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#18]

**Comment by jnallou** [comment]
Refining my diagram and working on creating more misuse cases

**Comment by MSMareddy** [comment]
Looks good so far, do you want to add a summary section as well? @jnallou

**Comment by malhuneidi** [comment]
Do we have to add summaries? I was not sure if we had to seemed like we already have alot of information in there in the other sections.

**Comment by malhuneidi** [comment]
Nevermind I re-read the assignment and I noticed he said "Summarize your observations" I'll go ahead and do that for mine now.

**Comment by jnallou** [comment]
@MSMareddy @nsabata  Added summary. My section should be complete. I'll go ahead and close this issue. Let me know if you have questions or concerns.
