### ISSUE TITLE
Mo's Use/Misuse Case

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#19]

**Comment by malhuneidi** [comment]
Let me know if you guys have any suggestions on mine =)!

**Comment by jnallou** [comment]
@malhuneidi Looks good Mo! Just one suggestion on the diagram. It looks like it has some white space at the bottom. Can you maybe try to remove that? Let me know if you have any questions about what I mean?

**Comment by malhuneidi** [comment]
I gotcha! Yeah I just noticed that too, I'll take care of that =)!

**Comment by MSMareddy** [comment]
Looks good Mo! I think you're good to close this issue.

**Comment by malhuneidi** [comment]
Sounds good!
