### ISSUE TITLE
Miti's Use/Misuse Case

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#20]

**Comment by MSMareddy** [comment]
I've gone through and completed this section, please feel free to let me know what you all think & make suggestions as well! @malhuneidi @JustinRobbins7 @jnallou @nsabata

**Comment by malhuneidi** [comment]
Looks great!

**Comment by jnallou** [comment]
You did an awesome job on the diagram! No suggestions on my end!
