### ISSUE TITLE
Part 2 - Security-Related config/install issues

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#22]

**Comment by JustinRobbins7** [comment]
Assigned to Joel and Miti

**Comment by jnallou** [comment]
I have added security configurations that Liberapay has taken and that user can do.

**Comment by MSMareddy** [comment]
I've added some more information about the overall type of documentation. There seems to be a lot of docs regarding payment processing platforms and security related to their integration with Liberapay. Also found a lot of docs in the past few years dealing with GDPR compliance and regulations.

**Comment by jnallou** [comment]
@nsabata This should be ready for review. Let us know if you have any questions or concerns.
