### ISSUE TITLE
Justin's Top Level Claim & Argument

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#30]

**Comment by JustinRobbins7** [comment]
Draft done

**Comment by JustinRobbins7** [comment]
Done with final version of document after fixing the problems found during the group proofreading.

**Comment by JustinRobbins7** [comment]
Added some context to a couple evidence nodes and updated some evidence nodes during evidence analysis.

**Comment by MSMareddy** [comment]
Diagram is looking good, read over your evidence and it looks solid. Thanks for laying out the format for evidence!
