### ISSUE TITLE
Miti's Top Level Claim & Argument

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#32]

**Comment by jnallou** [comment]
Hey Miti, next to your section header "1.4 Claim 4", can you add the text of your top claim for consistency?

For example, for mine, my header looks like "1.2 Claim 2 -  Liberapay minimizes unauthorized access to sensitive data"

**Comment by MSMareddy** [comment]
yeah I can, thanks!
