### ISSUE TITLE
Joel's Top Level Claim & Argument

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#33]

**Comment by jnallou** [comment]
Working on finishing up the assurance case. Should be ready for review soon.

**Comment by jnallou** [comment]
Ready for review!

**Comment by MSMareddy** [comment]
Assurance case looks good, and your evidence looks solid as well. Good job!

**Comment by nsabata** [comment]
Assurance case diagram is very well-thought out and has great evidence to support the claims
