### ISSUE TITLE
Mo's Top Level Claim & Argument

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#34]

**Comment by malhuneidi** [comment]
Adding my claim. Feel free to provide comments/suggestions guys =).

**Comment by jnallou** [comment]
Hey Mo, just couple of consistency notes. Next to your section header "1.3 Claim 3", can you add the text of your top claim for consistency?

For example, for mine, my head looks like "1.2 Claim 2 -  Liberapay minimizes unauthorized access to sensitive data"

Another thing in your diagram, you have two contexts. The first one has "Context CT1" but your second context does not have "Context CT2".

Also, I believe evidences should be nouns only, so you should try to update that in your diagram if you can.

**Comment by malhuneidi** [comment]
Thanks for your review! I've incorporated your feedback into my diagram and the title.

**Comment by jnallou** [comment]
Awesome, can you also adjust your top claim in your diagram? Right now, it has "Top-Claim C3" which conflicts with another claim in your diagram. Maybe change it to "Top-Claim C1"?

**Comment by malhuneidi** [comment]
Changed it to Top-Claim C1 =).

**Comment by jnallou** [comment]
Thank you.. Sorry, I have another one for ya ;) I think the arrow going from Rebuttal R1 to Context CT2 is backward. I'm not sure though. Can you verify?

**Comment by malhuneidi** [comment]
Good catch! I verified it and flipped it.

**Comment by jnallou** [comment]
Looks good on my end. Thanks for your quickness on this, Mo! :)

**Comment by malhuneidi** [comment]
No problem at all, thank you for your review =)!

**Comment by MSMareddy** [comment]
Hey Mo, your diagram looks good, surprised to see none of that exists in Liberapay, good work on the evidence!

**Comment by nsabata** [comment]
Claim looks great!
