### ISSUE TITLE
Part 2 - Evidence Alignment

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#35]
Everyone add in the evidence and alignment for your individual assurance cases.

So your sections look like:

Diagram

Things that exist

Things that don't exist (gaps)

**Comment by JustinRobbins7** [comment]
Added the evidence alignment section for claim 2.

**Comment by MSMareddy** [comment]
we can close this after reviewing everyones things in their individual tasks
