### ISSUE TITLE
Refine Final DFDs for Paper

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#48]
Collect and collect the DFDs that will be added into the paper for this module.

**Comment by JustinRobbins7** [comment]
Adapting my DFD for final DFD diagram.

**Comment by JustinRobbins7** [comment]
Adapted DFD according to instructor feedback.

**Comment by nsabata** [comment]
DFD has been finalized and added to Section 1 of the document.
