### ISSUE TITLE
OSS Threat Analysis Review

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#50]
Based on the threat analysis, review the OSS with respect to priority issues revealed by the DFDs and its threat analysis

**Comment by JustinRobbins7** [comment]
Threat division:
Nick: 1 - 9
Miti: 10 - 18
Joel: 19 - 29
Mo: 30 - 41

**Comment by MSMareddy** [comment]
@nsabata @jnallou @malhuneidi  - Observations looks good for the threat elements discussed, only issue might be inconsistent formatting between our sections, but thats not a biggie

**Comment by nsabata** [comment]
I added subsections to help distinguish which areas of the DFD are being addressed with each threat.
