### ISSUE TITLE
Perform Code Review

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#59]
Perform the code review that the document will be detailing.

**Comment by JustinRobbins7** [comment]
Miti - 2,4,5
Nick - 1,3,6
Mo - 7,8,9
Joel - 10,11,12

**Comment by MSMareddy** [comment]
Finished 2, 4, 5, and 1.3 bandit info

**Comment by malhuneidi** [comment]
Finished my sections (7-9) along with the SonarQube 1.3 info.

**Comment by MSMareddy** [comment]
Looks good Mo

**Comment by jnallou** [comment]
Finished 10,11,12. Please feel free to start reviewing.

I'll start looking at the other parts that are completed. :)

**Comment by nsabata** [comment]
Finished 1, 3, & 6 now so we've got manual code review findings covered for each of the CWE's in our checklist

**Comment by JustinRobbins7** [comment]
Excellent. Will get Section 2 going now.
