### ISSUE TITLE
Documentation - Proofreading

### ISSUE THREAD

**Issue by JustinRobbins7** [JustinRobbins7/CSCI-8420-Team-1#65]

**Comment by JustinRobbins7** [comment]
Found and fixed some typos found while writing section 2

**Comment by MSMareddy** [comment]
Looks good to me, didn't find any major grammar/ flow issues

**Comment by jnallou** [comment]
Finished review. looks great. just fixed couple of typos.

**Comment by nsabata** [comment]
Finished proofreading the document and found some formatting/grammar issues that I fixed.
